# Travis file to build a new image of the released crestdsl every day.
# This way, we push the latest version to hub.docker.com at least once a day.
# Also, we can figure out 
sudo: required

language: ruby

services:
  - docker

script:
  - docker build -t crestdsl/release:latest .
  # extract the crestdsl-version
  - crestdsl_version=`pip search crestdsl | awk -F'[()]' '{print $2}'`
  - docker tag crestdsl/release:latest crestdsl/release:${crestdsl_version}
  
  # check which images are now available
  - docker images
  
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  # push images to docker hub
  - docker push crestdsl/release:latest
  - docker push crestdsl/release:${crestdsl_version}
